name: rfc_6901
version: 0.1.0
description: JSON Pointer (RFC 6901). Reads/writes referred values in JSON documents.
homepage: "https://github.com/f3ath/rfc-6901-dart"

environment:
  sdk: '>=2.12.0-259 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.2
  test_coverage: ^0.5.0

