name: rfc_6901
version: 0.1.0
description: JSON Pointer (RFC 6901). Reads/writes referred values in JSON documents.
homepage: "https://github.com/f3ath/rfc-6901-dart"

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  check_coverage: ^0.0.3

cider:
  link_template:
    tag: https://github.com/f3ath/rfc-6901-dart/releases/tag/%tag% # initial release link template
    diff: https://github.com/f3ath/rfc-6901-dart/compare/%from%...%to% # subsequent releases link template